export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

// Division Crud Types
export const FETCH_DIVISIONS = "FETCH_DIVISIONS";
export const FETCH_DIVISION = "FETCH_DIVISION";
export const CREATE_DIVISION = "CREATE_DIVISION";
export const UPDATE_DIVISION = "UPDATE_DIVISION";
export const DELETE_DIVISION = "DELETE_DIVISION";

// District Crud Types
export const FETCH_DISTRICTS = "FETCH_DISTRICTS";
export const FETCH_DISTRICT = "FETCH_DISTRICT";
export const CREATE_DISTRICT = "CREATE_DISTRICT";
export const UPDATE_DISTRICT = "UPDATE_DISTRICT";
export const DELETE_DISTRICT = "DELETE_DISTRICT";

// Sub District Crud Types
export const FETCH_SUB_DISTRICTS = "FETCH_SUB_DISTRICTS";
export const FETCH_SUB_DISTRICTS_BY_DISTRICT_ID =
  "FETCH_SUB_DISTRICTS_BY_DISTRICT_ID";
export const FETCH_SUB_DISTRICT = "FETCH_SUB_DISTRICT";
export const CREATE_SUB_DISTRICT = "CREATE_SUB_DISTRICT";
export const UPDATE_SUB_DISTRICT = "UPDATE_SUB_DISTRICT";
export const DELETE_SUB_DISTRICT = "DELETE_SUB_DISTRICT";

// PostOffice Crud Types

export const FETCH_POST_OFFICES_BY_SUB_DISTRICT_ID =
  "FETCH_POST_OFFICES_BY_SUB_DISTRICT_ID";

export const CREATE_STAFF = "CREATE_STAFF";

// Utils Types
export const TOGGLE_MESSAGE = "TOGGLE_MESSAGE";
export const TOGGLE_LOADING = "TOGGLE_LOADING";
