export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

// Division Crud Types
export const FETCH_DIVISIONS = "FETCH_DIVISIONS";
export const FETCH_DIVISION = "FETCH_DIVISION";
export const CREATE_DIVISION = "CREATE_DIVISION";
export const UPDATE_DIVISION = "UPDATE_DIVISION";
export const DELETE_DIVISION = "DELETE_DIVISION";

// Utils Types
export const TOGGLE_MESSAGE = "TOGGLE_MESSAGE";
export const TOGGLE_LOADING = "TOGGLE_LOADING";
